---
- name: Import tasks configure.yaml
  ansible.builtin.import_tasks: configure.yaml
  tags: grafana

- name: Import tasks install.yaml
  ansible.builtin.import_tasks: install.yaml
  tags: grafana

- ansible.builtin.meta: flush_handlers
  tags: grafana
