---
# defaults file for loki
loki_user: loki
loki_group: loki
loki_uid: 903
loki_gid: 903

loki_docker_image: grafana/loki:latest
loki_network_name: monitoring
loki_http_listen_port: 3100
loki_http_listen_address: "0.0.0.0"
loki_expose_port: true
loki_base_directories:
  - "{{ loki_config_directory }}"
  - "{{ loki_working_path }}"
  - "{{ loki_common.storage.filesystem.rules_directory }}"
loki_config_directory: "/etc/loki"
loki_working_path: "/var/lib/loki"
loki_ruler_alert_path: "{{ loki_working_path }}/rules/custom"

# Default Variables for /etc/loki/config.yml
loki_auth_enabled: false
loki_target: "all"
loki_ballast_bytes: 0

loki_server:
  http_listen_address: "{{ loki_http_listen_address }}"
  http_listen_port: "{{ loki_http_listen_port }}"
  grpc_listen_port: 9096

loki_common:
  instance_addr: 127.0.0.1
  path_prefix: "{{ loki_working_path }}"
  storage:
    filesystem:
      chunks_directory: "{{ loki_working_path }}/chunks"
      rules_directory: "{{ loki_working_path }}/rules"
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

loki_query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

loki_schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

loki_ruler:
  storage:
    type: local
    local:
      directory: "{{ loki_working_path }}/rules"
  rule_path: "{{ loki_working_path }}/rules_tmp"
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  enable_alertmanager_v2: true
  alertmanager_url: http://alertmanager:9093

loki_analytics:
  reporting_enabled: false

loki_ruler_alerts:
  - name: Logs.sshd
    rules:
      - alert: SshLoginFailed
        expr: |
          count_over_time({job=~"secure"} |="sshd[" |~": Failed|: Invalid|: Connection closed by authenticating user" | __error__="" [15m]) > 15
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "{% raw %}SSH authentication failure (instance {{ $labels.instance }}).{% endraw %}"

# Additional Config Variables for /etc/loki/config.yml
# loki_distributor:
# loki_querier:
# loki_query_scheduler:
# loki_frontend:
# loki_ingester_client:
# loki_ingester:
# loki_index_gateway:
# loki_storage_config:
# loki_chunk_store_config:
# loki_compactor:
# loki_limits_config:
# loki_frontend_worker:
# loki_table_manager:
# loki_memberlist:
# loki_runtime_config:
# loki_operational_config:
# loki_tracing:
