---
- name: install | Create Loki as a docker container
  community.docker.docker_container:
    state: started
    name: loki
    image: "{{ loki_docker_image }}"
    user: "{{ loki_uid }}:{{ loki_gid }}"
    recreate: false
    restart_policy: always
    volumes:
      - "{{ loki_working_path }}:{{ loki_working_path }}"
      - "{{ loki_config_directory }}/config.yml:/etc/loki/local-config.yaml:ro"
    published_ports:
      - 3100:3100
    networks:
      - name: "{{ loki_network_name }}"
  become_user: "{{ loki_user }}"
  tags: loki


