---
prometheus_custom_targets:
  scrape_configs:
    - job_name: docker-node-exporter
      docker_sd_configs:
        - host: unix:///var/run/docker.sock
      relabel_configs:
        - source_labels: [ __meta_docker_container_label_prometheus_scrape ]
          regex: true.*
          action: keep
        - target_label: instance
          replacement: "{{ hostvars[inventory_hostname].ansible_nodename }}"
        - source_labels: [ __meta_docker_network_ip ]
          regex: (.+)
          target_label: __address__
          replacement: ${1}:9100
