---
alertmanager_image: prom/alertmanager
alertmanager_version: v0.27.0
alertnamager_network_name: monitoring
alertmanager_loki_url: "http://{{ hostvars[inventory_hostname].ansible_default_ipv4.address | default(hostvars[ansible_host].ansible_default_ipv4.address) }}:3100/loki/api/v1/push"

alertmanager_user: alertmanager
alertmanager_group: alertmanager
alertmanager_uid: 902
alertmanager_gid: 902
alertmanager_base_directories:
  - /etc/alertmanager
  - /var/lib/alertmanager

alertmanager_additional_command_args: ""

alertmanager_slack_webhook: webhook
alertmanager_slack_channel: fake
