---
- name: install | Get docker gid
  ansible.builtin.getent:
    database: group
    key: docker
  register: _docker_gid
  tags: prometheus

- name: install | Create prometheus as a docker container
  community.docker.docker_container:
    state: started
    command: |
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --web.console.libraries=/usr/share/prometheus/console_libraries
      --web.console.templates=/usr/share/prometheus/consoles
      {{ prometheus_additional_command_args }}
    image: "{{ prometheus_image }}:{{ prometheus_version }}"
    name: prometheus
    user: "{{ prometheus_uid }}:{{ _docker_gid.ansible_facts.getent_group.docker[1] }}"
    published_ports:
      - 9090:9090
    recreate: false
    restart_policy: always
    volumes:
      - /etc/prometheus/rules/:/etc/prometheus/rules/:ro
      - /etc/prometheus/targets/:/etc/prometheus/targets/:ro
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /var/lib/prometheus:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock
    log_driver: loki
    log_options:
      loki-url: "http://{{ hostvars[ansible_host].ansible_default_ipv4.address }}:3100/loki/api/v1/push"
      loki-retries: "5"
      loki-batch-size: "400"
    networks:
      - name: "{{ prometheus_network_name }}"
  become_user: "{{ prometheus_user }}"
  tags: prometheus
