---
dependencies:
  - role: common/users
    vars:
      users_groups:
        - name: "{{ loki_group }}"
          gid: "{{ loki_gid }}"
      users:
        - name: "{{ loki_user }}"
          uid: "{{ loki_uid }}"
          groups:
            - "{{ loki_group }}"
            - docker
