---
prometheus_image: prom/prometheus
prometheus_version: v2.51.2
prometheus_network_name: monitoring
prometheus_loki_url: "http://{{ hostvars[inventory_hostname].ansible_default_ipv4.address | default(hostvars[ansible_host].ansible_default_ipv4.address) }}:3100/loki/api/v1/push"

prometheus_user: prometheus
prometheus_group: prometheus
prometheus_uid: 900
prometheus_gid: 900
prometheus_base_directories:
  - /etc/prometheus
  - /etc/prometheus/rules
  - /etc/prometheus/targets
  - /var/lib/prometheus

prometheus_additional_command_args: |
  --web.enable-lifecycle

prometheus_custom_targets: []
prometheus_custom_rules: {}
