---
- import_playbook: gcp_compute.yaml
  vars:
    gcp_compute_name: monitoring-stack
    gcp_compute_group: monitoring_stack
    gcp_compute_fw_ports:
      - 9090
    gcp_compute_fw_source_ranges:
      - 81.202.93.170/32
  tags: always

- hosts: monitoring_stack
  gather_facts: true
  roles:
    - role: "common/users"
    - role: "common/packages"
    - role: "common/docker"
    - role: "prometheus_exporters/node_exporter"
    - role: "prometheus"
